on:
  push:
  pull_request:
  schedule:
    # Run daily to keep sccache cache up to date.
    - cron: '13 4 * * *'
jobs:
  # We need to build our own sccache until e6326bc8a20ee06af37e16a3a7a14e3374c66c66
  # is in a released version.
  sccache:
    runs-on: 'macos-10.15'
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal

      - uses: actions/checkout@v2
        with:
          repository: mozilla/sccache
          # Update cache key if this changes.
          ref: e6326bc8a20ee06af37e16a3a7a14e3374c66c66
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-sccache-${{ hashFiles('Cargo.lock') }}-0

      - name: Build sccache
        run: |
          cargo build --release

      - name: Upload sccache executable
        uses: actions/upload-artifact@v2
        with:
          name: sccache
          path: target/release/sccache

  pythonbuild:
    runs-on: 'macos-10.15'
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-pythonbuild-${{ hashFiles('Cargo.lock') }}

      - name: Build
        run: |
          cargo build --release

      - name: Upload pythonbuild Executable
        uses: actions/upload-artifact@v2
        with:
          name: pythonbuild
          path: target/release/pythonbuild

  toolchain:
    needs:
      - sccache
    runs-on: 'macos-10.15'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SCCACHE_BUCKET: 'python-build-standalone-sccache'
      SCCACHE_S3_USE_SSL: '1'
    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Download sccache
        uses: actions/download-artifact@v2
        with:
          name: sccache

      - name: Start sccache
        run: |
          chmod +x sccache
          ./sccache --start-server

      - name: Build
        run: |
          python3.9 ./build-macos.py --make-target toolchain

      - name: Stop sccache
        run: |
          ./sccache -s

      - name: Upload Toolchain Archive
        uses: actions/upload-artifact@v2
        with:
          name: toolchain
          path: build/clang-*.tar

  build:
    strategy:
      fail-fast: false
      matrix:
        py:
          - 'cpython-3.8'
          - 'cpython-3.9'
        optimizations:
          - 'debug'
          - 'pgo'
    needs:
      - pythonbuild
      - toolchain
    runs-on: 'macos-10.15'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Download pythonbuild
        uses: actions/download-artifact@v2
        with:
          name: pythonbuild
          path: build

      - name: Download toolchain
        uses: actions/download-artifact@v2
        with:
          name: toolchain
          path: build

      - name: Build
        run: |
          ./build-macos.py --skip-toolchain --python ${{ matrix.py }} --optimizations ${{ matrix.optimizations }}

      - name: Validate Distribution
        run: |
          chmod +x build/pythonbuild
          build/pythonbuild validate-distribution dist/*.tar.zst

      - name: Upload Distributions
        uses: actions/upload-artifact@v2
        with:
          name: dists-macos
          path: dist/*
